local cache_dir = os.getenv('HOME') .. '/.cache/nvim/'

vim.cmd.syntax('off')
vim.opt.backupdir = cache_dir .. 'backup/'
vim.opt.bg = 'dark'
vim.opt.ch = 0
vim.opt.clipboard = 'unnamedplus'
vim.opt.cmdheight = 0
vim.opt.colorcolumn = "120"
vim.opt.completeopt = 'menu,menuone,noselect'
vim.opt.conceallevel = 2
vim.opt.directory = cache_dir .. 'swag/'
vim.opt.expandtab = true
vim.opt.fillchars = 'fold: ,vert:│,eob: ,msgsep:‾'
vim.opt.foldenable = false
vim.opt.guifont = 'MonoLisa Nerd Font:h15'
vim.opt.hidden = true
vim.opt.laststatus = 3
vim.opt.matchtime = 1
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.sessionoptions = 'buffers,curdir,folds,help,tabpages,winsize'
vim.opt.shiftwidth = 2
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.signcolumn = 'yes'
vim.opt.softtabstop = 2
vim.opt.spellfile = cache_dir .. 'spell/en.uft-8.add'
vim.opt.spelllang = 'en'
vim.opt.splitkeep = 'screen'
vim.opt.splitright = true
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.timeout = true
vim.opt.timeoutlen = 300
vim.opt.ttimeoutlen = 0
vim.opt.undodir = cache_dir .. 'undo/'
vim.opt.undofile = true
vim.opt.updatetime = 50
vim.opt.viewdir = cache_dir .. 'view/'
vim.opt.wrap = true
vim.opt.equalalways = false -- prevent auto-resize when switching windows (keeps Claude Code split fixed)
-- vim.opt if for things you would set in vimscript. vim.g is for things you'd let.
vim.g.mapleader = ' '
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
