vim.cmd [[syntax off]]
vim.opt.termguicolors = true
vim.opt.bg = 'dark'
vim.opt.showcmd = true
vim.opt.number = true
vim.opt.cmdheight = 1
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.splitright = true
vim.opt.mouse = 'a'
vim.opt.wrap = true
vim.opt.signcolumn = 'yes'
vim.opt.completeopt = 'menu,menuone,noselect'
vim.opt.hidden = true
vim.opt.undofile = true
vim.opt.undodir = vim.fn.stdpath('config') .. '/vimundo'
vim.opt.spelllang = 'en'
vim.opt.showmatch = true
vim.opt.matchtime = 1
vim.opt.updatetime = 50
vim.opt.timeoutlen = 400
vim.opt.ttimeoutlen = 0
vim.opt.laststatus = 3
vim.opt.fillchars = 'fold: ,vert:│,eob: ,msgsep:‾'
vim.opt.guifont = 'MonoLisa Nerd Font:h15'
