complete -c jira-terminal -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "transition" -d 'Transition of ticket across status.'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "list" -d 'List the issues from JIRA.'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "detail" -d 'Detail of a JIRA tickets..'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "alias" -d 'Configuration for alias. One of add,list or remove is required.'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "fields" -d 'List of possible Fields for details...'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "assign" -d 'Assign a ticket to user.'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "comment" -d 'List or add comments to a ticket. Default action is adding.'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "update" -d 'Update a field for a ticket'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "autocompletion" -d 'Generate autocompletion script..'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "new" -d 'Create a new ticket.'
complete -c jira-terminal -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c jira-terminal -n "__fish_seen_subcommand_from transition" -s t -l ticket -d 'Ticket ID from JIRA.'
complete -c jira-terminal -n "__fish_seen_subcommand_from transition" -s l -l list -d 'List the possible transitions.'
complete -c jira-terminal -n "__fish_seen_subcommand_from transition" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from transition" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s p -l project -d 'Project Code to filter with.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s a -l assignee -d 'Assignee username or email to filter with.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s c -l component -d 'Component name or ID to filter with.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s d -l display
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s e -l epic -d 'EPIC name or issue key of epic to filter with.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s f -l filter -d 'Filter name or filter id that you saved in JIRA.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s j -l jql -d 'JQL Query or alias to JQL query to filter with.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s l -l label -d 'Search for issues with a label or list of labels.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s m -l main -d 'Search for subtask of a particular issue.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s P -l priority -d 'Search for issues with a particular priority.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s r -l reporter -d 'Search for issues that were reported by a particular user.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s s -l sprint -d 'Search for issues that are assigned to a particular sprint.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s S -l status -d 'Search for issues that have a particular status.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s t -l type -d 'Search for issues that have a particular issue type. '
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s T -l text -d 'This is a master-field that allows you to search all text fields for issues.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s C -l count -d 'Total number of issues to show. (Default is 50)'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s o -l offset -d 'Offset to start the first item to return in a page of results. (Default is 0)'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s A -l alias -d 'Save the applied options as an alias. You can use it with jql option later.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s M -l me -d 'Issues assigned to you.'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s J -l json -d 'JSON response'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from detail" -s f -l fields
complete -c jira-terminal -n "__fish_seen_subcommand_from detail" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from detail" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from alias" -s a -l add -d 'Value to associate with provided alias name.'
complete -c jira-terminal -n "__fish_seen_subcommand_from alias" -s l -l list -d 'List the alias saved.'
complete -c jira-terminal -n "__fish_seen_subcommand_from alias" -s r -l remove -d 'List the alias saved.'
complete -c jira-terminal -n "__fish_seen_subcommand_from alias" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from alias" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from fields" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from fields" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from assign" -s u -l user -d 'Assign the ticket to the provided user.'
complete -c jira-terminal -n "__fish_seen_subcommand_from assign" -s t -l ticket -d 'Ticket to use.'
complete -c jira-terminal -n "__fish_seen_subcommand_from assign" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from assign" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from comment" -s b -l body -d 'Body of the comment. To mention someone, you can use @(query) The query can include jira username or display name or email address.'
complete -c jira-terminal -n "__fish_seen_subcommand_from comment" -s t -l ticket -d 'Ticket to use.'
complete -c jira-terminal -n "__fish_seen_subcommand_from comment" -s l -l list -d 'List all the comments of a ticket.'
complete -c jira-terminal -n "__fish_seen_subcommand_from comment" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from comment" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from update" -s f -l field -d 'Key of field to update. You can use jira-terminal fields <TICKET> to see possible set of keys.'
complete -c jira-terminal -n "__fish_seen_subcommand_from update" -s v -l value -d 'Value of the field to update.'
complete -c jira-terminal -n "__fish_seen_subcommand_from update" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from update" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from autocompletion" -s s -l shell
complete -c jira-terminal -n "__fish_seen_subcommand_from autocompletion" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from autocompletion" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s P -l project -d 'Project Key to create the ticket.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s m -l main -d 'Main ticket to create the sub-ticket.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s t -l type -d 'Issue type for new ticket.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s l -l labels -d 'Comma separated list of labels.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s p -l priority -d 'Priority Of the ticket.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s s -l summary -d 'Summary of ticket'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s d -l description -d 'Description of ticket'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s c -l components -d 'Comma separated list of components of ticket'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s a -l assignee -d 'Assignee email of ticket'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s C -l custom -d 'Comma separated value pair for custom fields. You can use alias in value or key itself. Example- "customfield_12305:value,alias_to_key:value2. You can use fields subcommand to check the list of custom fields available. '
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s M -l minimal -d 'Only summary and description will be asked if not available.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s q -l quiet -d 'Do not ask for missing options.'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from new" -s V -l version -d 'Prints version information'
complete -c jira-terminal -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c jira-terminal -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
