# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
- title: Needs My Review
  filters: is:open review-requested:@me
- title: My Pull Requests
  filters: is:open author:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  keybindings:
  prs:
    - key: C
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c ":Octo pr edit {{.PrNumber}}" .
        '
repoPaths:
  Boulevard/*: ~/Developer/Boulevard/*
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: delta
